import "./globals.css";
import { Open_Sans } from "next/font/google";
import Navigator from "./components/navigator";
import Footer from "./components/footer";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className}`}>
        <Navigator />
        {children}
        <Footer />
      </body>
    </html>
  );
}
