import "./globals.css";
import { Open_Sans } from "next/font/google";
import Footer from "./components/footer";
import 'animate.css';


const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
